### ISSUE TITLE
Custom path option

### ISSUE THREAD

**Issue by tivac** [voodoochild/rollup-plugin-i18n-csv#2]
Since I'm using [`translate.js`](https://github.com/StephanHoyer/translate.js) but want to keep period-separated translation keys I can't use this plugin currently. If it accepted an optional function to generate the final path passed to `lodash.set` (with the default matching the current behavior) it'd be a bit more flexible.

Something like this:

```js
import i18nCsv from "rollup-plugin-i18n-csv";

export default {
    entry   : "src/index.js",
    targets : [
        { dest : pkg.module, format : "es" }
    ],
    plugins  : [
        i18nCsv({
            path : ({ key, field, value }) => {
                // Default implementation
                return `${field}.${row.key}`;

                // Or a custom implementation that creates shallow objects
                return [ field, key ]
            }
        })
    ]
};
```

**Comment by voodoochild** [comment]
Added in c8547cfb2e9acb69df60dfeb7469a66eff8c52e9
